from tkinter import *
win=Tk()
win.title("Age Calculator")
frame1=Frame(win,width=400,height=400,bg="lightblue")
frame1.grid(row=0,column=0,padx=10,pady=10)
label1=Label(frame1,text="Enter your birth year:",bg="lightblue",font=("Times",18))
label1.grid(row=1,column=0,padx=10,pady=10)
display=Entry(frame1,width=10,font=("Times",18))
display.grid(row=1,column=1,padx=10,pady=10)
label2=Label(frame1,text="Present year:",bg="lightblue",font=("Times",18))
label2.grid(row=2,column=0,padx=10,pady=10)
present_year=Entry(frame1,width=10,font=("Times",18))
present_year.insert(END,"2026")
present_year.grid(row=2,column=1,padx=10,pady=10)
def cal():
    Birty_year=int(display.get())
    Present_year=int(present_year.get())
    age=Present_year-Birty_year
    result_dis.delete(0,END)
    result_dis.insert(END,str(age))
result_btn=Button(frame1,text="Calculate Age",command=cal,bg="lightgreen",font=("Times",14))
result_btn.grid(row=4,column=0,padx=10,pady=10)
result_label=Label(frame1,text="age  ",bg="lightblue",font=("Times",18))
result_label.grid(row=3,column=0,padx=10,pady=10)
result_dis=Entry(frame1,width=15,font=("Times",18))
result_dis.grid(row=3,column=1,padx=10,pady=10)
win.mainloop()
